-- Active: 1698868817748@@127.0.0.1@3306@7tech
CREATE DATABASE 7TECH;

USE 7TECH;

CREATE TABLE USER(
    ID_USER INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(90),
    EMAIL VARCHAR(90),
    SENHA VARCHAR(90) NOT NULL,
    DATA_NASC DATE
)

SELECT * FROM USER ;

DROP PROCEDURE INSERT_USER;
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_USER`(
    NOME_USER VARCHAR(80),
    DATA_NASC DATE,
    EMAIL_USER VARCHAR(80),
    SENHA_USER VARCHAR(20)
)
BEGIN
    INSERT INTO USER (NOME, DT_NASC, EMAIL,SENHA) VALUES (
        NOME_USER,
        DATA_NASC,
        EMAIL_USER,
        SENHA_USER
    )

