-- Active: 1701479864696@@viaduct.proxy.rlwy.net@35426@railway

-- DEFINIÇÃO DE USUARIO ROOT ADD

CREATE USER 'ROOT'@'localhost' IDENTIFIED BY 'SEVEN777';
GRANT ALL PRIVILEGES ON 7code.* TO 'ROOT'@'localhost';
FLUSH PRIVILEGES;
