-- Active: 1699889862379@@127.0.0.1@3306@7tech
CREATE DATABASE 7TECH;

USE 7TECH;

CREATE TABLE USER (
    ID_USER INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(90) NOT NULL,
    EMAIL VARCHAR(90) NOT NULL,
    SENHA VARCHAR(90) NOT NULL,
    DATA_NASC DATE
);



CREATE TABLE BANKACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INTEGER,
    SALDO DECIMAL(10,2) DEFAULT 0.00,
    ACCOUNT_TYPE VARCHAR(80) DEFAULT 'CORRENTE',
    IS_ENABLE BIT DEFAULT 1,
    DATA_ABERTURA DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);


