DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_USER`(
    NOME_USER VARCHAR(90),
    EMAIL_USER VARCHAR(90),
    DATA_NASC_USER DATE,
    SENHA_USER VARCHAR(90)
)
BEGIN
    INSERT INTO user (NOME, EMAIL, DATA_NASC, SENHA) VALUES (
        NOME_USER,
        EMAIL_USER,
        DATA_NASC_USER,
        SENHA_USER
    );
END;
//